spring.datasource.url=jdbc:h2:file:./data/barbearia-dev;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.flyway.enabled=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

app.initial-admin.login=${APP_INITIAL_ADMIN_USERNAME:admin}
app.initial-admin.password=${APP_INITIAL_ADMIN_PASSWORD:admin12345}
app.initial-admin.name=${APP_INITIAL_ADMIN_NAME:Administrador}
app.demo-data=${APP_DEMO_DATA:true}
